export const ErrorCodes = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

  // User Profile Errors
  PROFILE_VALIDATION_ERROR: "PROFILE_VALIDATION_ERROR",
  AVATAR_UPLOAD_ERROR: "AVATAR_UPLOAD_ERROR",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",

  // Identity & Access Errors
  EMAIL_VALIDATION_ERROR: "EMAIL_VALIDATION_ERROR",
  PASSWORD_VALIDATION_ERROR: "PASSWORD_VALIDATION_ERROR",
  IDENTITY_VALIDATION_ERROR: "IDENTITY_VALIDATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  TOKEN_REUSE_DETECTED: "TOKEN_REUSE_DETECTED",

  // Social & Friend Errors
  SOCIAL_FRIEND_VALIDATION_ERROR: "SOCIAL_FRIEND_VALIDATION_ERROR",
  SOCIAL_FRIEND_CONFLICT_ERROR: "SOCIAL_FRIEND_CONFLICT_ERROR",

  // Photo Sharing Errors
  PHOTO_SHARING_VALIDATION_ERROR: "PHOTO_SHARING_VALIDATION_ERROR",
  PHOTO_SHARING_CONFLICT_ERROR: "PHOTO_SHARING_CONFLICT_ERROR",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
